import { NextResponse } from "next/server";
import { Nango } from "@nangohq/node";
import { extractNangoAccessToken } from "@/lib/nangoToken";

const nango = new Nango({ secretKey: process.env.NANGO_SECRET_KEY || "" });

export async function POST(req: Request) {
    try {
        const { connectionId, owner, repo, filePath, newContent } = await req.json();

        if (!connectionId || !owner || !repo || !filePath || !newContent) {
            return NextResponse.json({ error: "Missing required parameters" }, { status: 400 });
        }

        const tokenResponse = await nango.getToken("github-getting-started", connectionId);
        const token = extractNangoAccessToken(tokenResponse as any);
        
        const headers = {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github.v3+json",
            "Content-Type": "application/json"
        };

        // 1. Get default branch
        const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers });
        if (!repoRes.ok) throw new Error("Failed to get repo info");
        const repoData = await repoRes.json();
        const defaultBranch = repoData.default_branch;

        // 2. Get latest commit SHA
        const refRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`, { headers });
        if (!refRes.ok) throw new Error("Failed to get branch ref");
        const refData = await refRes.json();
        const baseSha = refData.object.sha;

        // 3. Create new branch
        const branchName = `docs/update-comments-${Date.now()}`;
        const newRefRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
            method: "POST",
            headers,
            body: JSON.stringify({
                ref: `refs/heads/${branchName}`,
                sha: baseSha
            })
        });
        if (!newRefRes.ok) throw new Error("Failed to create new branch");

        // 4. Get file's current SHA
        const fileRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}?ref=${defaultBranch}`, { headers });
        let fileSha = undefined;
        if (fileRes.ok) {
            const fileData = await fileRes.json();
            fileSha = fileData.sha;
        }

        // 5. Update/Create file
        const updateRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, {
            method: "PUT",
            headers,
            body: JSON.stringify({
                message: `docs: Add AI generated comments for ${filePath}`,
                content: Buffer.from(newContent).toString("base64"),
                branch: branchName,
                sha: fileSha
            })
        });
        if (!updateRes.ok) throw new Error("Failed to update file contents");

        // 6. Create Pull Request
        const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
            method: "POST",
            headers,
            body: JSON.stringify({
                title: `docs: Enhance documentation for ${filePath}`,
                head: branchName,
                base: defaultBranch,
                body: "This PR was automatically generated by CodeComm AI to add comprehensive documentation to the code."
            })
        });
        if (!prRes.ok) throw new Error("Failed to create Pull Request");
        
        const prData = await prRes.json();
        
        return NextResponse.json({ 
            success: true, 
            pullRequestUrl: prData.html_url 
        });

    } catch (err: any) {
        console.error("PR Creation error:", err);
        return NextResponse.json({ error: err.message }, { status: 500 });
    }
}
