import { NextResponse } from 'next/server';
import { createOpenAI } from '@ai-sdk/openai';
import { generateText } from 'ai';
import { commitAndCreatePrManual } from '../../../mastra/tools/githubTools';

const openrouter = createOpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY || process.env.OPENAI_API_KEY,
});

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { connectionId, owner, repo, file, issue, code_snippet, secure_fix } = body;

        if (!connectionId || !owner || !repo || !file || !issue) {
            console.error("Missing required fields for fix-issue", body);
            return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
        }

        console.log(`[Fix Issue] Generating secure snippet for ${file}...`);
        
        // 1. Generate the exact replacement code snippet using Vercel AI SDK directly
        // This avoids Mastra's tool-calling requirement which the stepfun free model rejects
        const result = await generateText({
            model: openrouter("stepfun/step-3.5-flash:free"),
            system: `You are a strict secure coding assistant. Your ONLY job is to output the exact replacement code snippet to fix a vulnerability.
RULES:
1. Return ONLY the raw code snippet that will exactly replace the vulnerable snippet.
2. DO NOT use markdown code fences (no \`\`\`python).
3. DO NOT output any explanations, greetings, or thoughts.
4. Maintain the exact indentation of the original snippet.`,
            prompt: `Apply the following secure fix strategy to the vulnerable snippet.

Vulnerable Snippet:
${code_snippet || 'N/A'}

Secure Fix Strategy:
${secure_fix || 'N/A'}`,
        });

        const replacementSnippet = result.text.trim();
        console.log(`[Fix Issue] Generated Snippet:\n`, replacementSnippet);

        if (!replacementSnippet || replacementSnippet === code_snippet) {
             throw new Error("Failed to generate a valid replacement snippet.");
        }

        // 2. Prepare PR details
        const uniqueId = Math.random().toString(36).substring(2, 8);
        const newBranch = `fix/${issue.toLowerCase().replace(/[^a-z0-9]/g, '-')}-${uniqueId}`;
        const prTitle = `Fix ${issue} vulnerability`;
        const prBody = `This PR automatically resolves the following vulnerability:\n\n**Issue**: ${issue}\n**Strategy Applied**: ${secure_fix}\n\nGenerated by CodeComm AI.`;
        const commitMessage = `Fix vulnerability: ${issue}`;

        console.log(`[Fix Issue] Manually executing commitAndCreatePrManual... branch: ${newBranch}`);

        // 3. Manually execute the GitHub commit/PR tool
        let prResult: any;
        try {
            prResult = await commitAndCreatePrManual({
                connectionId,
                owner,
                repo,
                baseBranch: 'main', // Standard fallback base branch
                newBranch,
                path: file,
                targetSnippet: code_snippet,
                replacementSnippet,
                commitMessage,
                prTitle,
                prBody
            });
        } catch (githubErr: any) {
            // Check if baseBranch was wrong
            if (githubErr.message?.includes('Not Found') || githubErr.message?.includes('base branch')) {
                console.log(`[Fix Issue] 'main' branch failed, trying 'master'...`);
                prResult = await commitAndCreatePrManual({
                     connectionId, owner, repo,
                     baseBranch: 'master',
                     newBranch, path: file,
                     targetSnippet: code_snippet, replacementSnippet, commitMessage, prTitle, prBody
                });
            } else {
                throw githubErr;
            }
        }

        console.log(`[Fix Issue] Success: PR Created at ${prResult.pr_url}`);
        
        return NextResponse.json({ 
            success: true, 
             message: `Successfully created PR #${prResult.number}. [View PR On GitHub](${prResult.pr_url})` 
        });

    } catch (error: any) {
        console.error("Fix Issue API Error:", error.message || error);
        return NextResponse.json({ error: error.message || "Failed to fix issue" }, { status: 500 });
    }
}
